# Generated by Django 5.1.1 on 2024-10-26 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobs_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='email',
        ),
        migrations.AddField(
            model_name='jobs',
            name='desc',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
