# Generated by Django 5.1.1 on 2024-10-26 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_jobs_email_jobs_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='dead',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='desc',
            field=models.TextField(max_length=100),
        ),
    ]
