# Generated by Django 5.1.1 on 2024-10-27 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('exp', models.CharField(blank=True, max_length=200)),
                ('skills', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15, unique=True)),
                ('Users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='data',
        ),
    ]
