# Generated by Django 4.2.16 on 2024-10-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_datas_delete_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datas',
            old_name='Users',
            new_name='user',
        ),
    ]
