# Generated by Django 4.2.16 on 2024-11-07 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_datas_age_applyjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='name',
        ),
        migrations.AddField(
            model_name='applyjob',
            name='types',
            field=models.ForeignKey(default=1, max_length=201, on_delete=django.db.models.deletion.CASCADE, to='app.jobs'),
            preserve_default=False,
        ),
    ]
