# Generated by Django 4.2.16 on 2024-11-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_applyjob_name_applyjob_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyjob',
            old_name='types',
            new_name='type',
        ),
    ]
