# Generated by Django 4.2.16 on 2024-11-07 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_rename_types_applyjob_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='user',
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='type',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
