# Generated by Django 4.2.16 on 2024-11-07 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_applyjob_user_alter_applyjob_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='type',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='app.jobs'),
        ),
    ]
