# Generated by Django 4.2.16 on 2024-11-07 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_alter_applyjob_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='type',
        ),
        migrations.AddField(
            model_name='applyjob',
            name='types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.jobs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applyjob',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
