# Generated by Django 4.2.16 on 2024-11-07 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_applyjob_type_applyjob_types_applyjob_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyjob',
            old_name='types',
            new_name='job',
        ),
    ]
