# Generated by Django 4.2.16 on 2024-11-12 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_types_applyjob_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='age',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a', to='app.datas'),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='exp',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c', to='app.datas'),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='phone',
            field=models.ForeignKey(blank=True, max_length=15, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='e', to='app.datas', unique=True),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='qualification',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b', to='app.datas'),
        ),
        migrations.AddField(
            model_name='applyjob',
            name='skills',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='d', to='app.datas'),
        ),
    ]
