# Generated by Django 4.2.16 on 2024-11-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_applyjob_age_applyjob_exp_applyjob_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyjob',
            name='age',
        ),
        migrations.RemoveField(
            model_name='applyjob',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='applyjob',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='applyjob',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='applyjob',
            name='skills',
        ),
    ]
